-- CreateTable
CREATE TABLE `clientes` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `NOME` VARCHAR(80) NULL DEFAULT '',
    `FANTASIA` VARCHAR(50) NULL DEFAULT '',
    `CPF_CNPJ` VARCHAR(14) NULL DEFAULT '',
    `RG_IE` VARCHAR(14) NULL DEFAULT '',
    `RUA` VARCHAR(80) NULL DEFAULT '',
    `BAIRRO` VARCHAR(30) NULL DEFAULT '',
    `CIDADE` VARCHAR(40) NULL DEFAULT '',
    `ESTADO` VARCHAR(2) NULL DEFAULT '',
    `CEP` VARCHAR(10) NULL DEFAULT '',
    `COMPLEMENTO` VARCHAR(80) NULL DEFAULT '',
    `NUMERO` INTEGER NULL DEFAULT 0,
    `OBS` VARCHAR(100) NULL DEFAULT '',
    `EMAIL` VARCHAR(50) NULL DEFAULT '',
    `TELEFONE` VARCHAR(20) NULL DEFAULT '',
    `STATUS` CHAR(1) NULL DEFAULT 'A',
    `VLR_TOTAL_VENDAS` DECIMAL(13, 2) NULL DEFAULT 0.00,

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `clientes_exportacao` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `NOME` VARCHAR(80) NULL DEFAULT '',
    `FANTASIA` VARCHAR(50) NULL DEFAULT '',
    `CPF_CNPJ` VARCHAR(18) NULL DEFAULT '',
    `RG_IE` VARCHAR(14) NULL DEFAULT '',
    `RUA` VARCHAR(80) NULL DEFAULT '',
    `BAIRRO` VARCHAR(30) NULL DEFAULT '',
    `CIDADE` VARCHAR(40) NULL DEFAULT '',
    `ESTADO` VARCHAR(2) NULL DEFAULT '',
    `CEP` VARCHAR(10) NULL DEFAULT '',
    `COMPLEMENTO` VARCHAR(80) NULL DEFAULT '',
    `NUMERO` INTEGER NULL DEFAULT 0,
    `OBS` VARCHAR(100) NULL DEFAULT '',
    `EMAIL` VARCHAR(50) NULL DEFAULT '',
    `TELEFONE` VARCHAR(20) NULL DEFAULT '',
    `STATUS` CHAR(1) NULL DEFAULT 'A',

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `condpgto` (
    `CODIGO` INTEGER NOT NULL,
    `CONDPGTO` VARCHAR(30) NULL DEFAULT '',
    `PARCELAS` INTEGER NULL DEFAULT 0,
    `INTERVALO` VARCHAR(4) NULL DEFAULT '0',

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `config` (
    `TAXA_JUROS` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VERSAO_SERVIDOR` INTEGER NULL DEFAULT 0,
    `GERA_LOG_TXT` CHAR(1) NULL DEFAULT 'S',
    `ALTERA_PRECOS` BOOLEAN NULL DEFAULT false
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `forma_pagamento` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `NOME` VARCHAR(50) NULL DEFAULT '',

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pedido` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `DATA` DATE NULL DEFAULT ('0000-00-00'),
    `HORA` TIME(0) NULL DEFAULT ('00:00:00'),
    `CLIENTE` INTEGER NULL DEFAULT 0,
    `VENDEDOR` INTEGER NULL DEFAULT 0,
    `OBS_PEDIDO` VARCHAR(60) NULL DEFAULT '',
    `OBS_NFE` VARCHAR(60) NULL DEFAULT '',
    `VLR_PRODUTOS` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `PERC_DESCONTO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VLR_DESCONTO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `PERC_ACRESCIMO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VLR_ACRESCIMO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VLR_TOTAL` DECIMAL(13, 2) NULL DEFAULT 0.00,

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pedido_item` (
    `PEDIDO` INTEGER NULL DEFAULT 0,
    `DATA` DATE NULL DEFAULT ('0000-00-00'),
    `HORA` TIME(0) NULL DEFAULT ('00:00:00'),
    `ITEM` INTEGER NULL DEFAULT 0,
    `PRODUTO` INTEGER NULL DEFAULT 0,
    `QUANTIDADE` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `UNIDADE` VARCHAR(3) NULL DEFAULT '',
    `VLR_VENDA` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VLR_UNITARIO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `PERC_DESCONTO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VLR_DESCONTO` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `VLR_TOTAL` DECIMAL(13, 2) NULL DEFAULT 0.00
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `pedido_pagamento` (
    `PEDIDO` INTEGER NULL DEFAULT 0,
    `FORMA_PAGAMENTO` INTEGER NULL DEFAULT 0,
    `VALOR` DECIMAL(13, 2) NULL DEFAULT 0.00
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `produtos` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `NOME` VARCHAR(50) NULL DEFAULT '',
    `UNIDADE` VARCHAR(3) NULL DEFAULT '',
    `VLR_VENDA` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `ESTOQUE` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `GRUPO` INTEGER NULL DEFAULT 0,
    `GRUPO_NOME` VARCHAR(50) NULL DEFAULT '',
    `SUBGRUPO` INTEGER NULL DEFAULT 0,
    `SUBGRUPO_NOME` VARCHAR(50) NULL DEFAULT '',
    `MARCA` INTEGER NULL DEFAULT 0,
    `MARCA_NOME` VARCHAR(50) NULL DEFAULT '',
    `FORNECEDOR` INTEGER NULL DEFAULT 0,
    `FORNECEDOR_NOME` VARCHAR(50) NULL DEFAULT '',

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `titulos` (
    `CODIGO` INTEGER NOT NULL AUTO_INCREMENT,
    `CLIENTE` INTEGER NULL DEFAULT 0,
    `TITULO` VARCHAR(10) NULL DEFAULT '',
    `PARCELA` INTEGER NULL DEFAULT 0,
    `VENCIMENTO` DATE NULL DEFAULT ('0000-00-00'),
    `VALOR` DECIMAL(13, 2) NULL DEFAULT 0.00,
    `CODVENDA` INTEGER NULL DEFAULT 0,

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `vendedores` (
    `CODIGO` INTEGER NOT NULL DEFAULT 0,
    `NOME` VARCHAR(50) NULL DEFAULT '',
    `USUARIO` VARCHAR(30) NULL DEFAULT '',
    `SENHA` VARCHAR(30) NULL DEFAULT '',

    PRIMARY KEY (`CODIGO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

